import { Holiday } from '@/types';

export const WIKI_SOURCES: Partial<Record<Holiday, string[]>> = {
  Halloween: [
    'https://en.wikipedia.org/wiki/List_of_Halloween_television_specials',
    'https://en.wikipedia.org/wiki/List_of_films_set_around_Halloween',
  ],
  Thanksgiving: [
    'https://en.wikipedia.org/wiki/List_of_Thanksgiving_television_specials',
  ],
  Christmas: [
    'https://en.wikipedia.org/wiki/List_of_Christmas_television_specials',
    'https://en.wikipedia.org/wiki/List_of_Christmas_films',
  ],
  "Valentine's Day": [
    'https://en.wikipedia.org/wiki/List_of_Valentine%27s_Day_television_specials',
  ],
  Easter: [
    'https://en.wikipedia.org/wiki/List_of_Easter_television_specials',
  ],
  'Independence Day': [
    'https://en.wikipedia.org/wiki/Category:Films_set_on_the_Fourth_of_July',
  ],
};

export const CURATED_KEYWORDS: Record<Holiday, string[]> = {
  Christmas: [
    '\\bChristmas\\b',
    '\\bX[- ]?mas\\b',
    '\\bHoliday Special\\b',
    '\\bSanta\\b',
    '\\bSt[.]?\\s?Nick\\b',
    '\\bKris Kringle\\b',
    '\\bNorth Pole\\b',
    '\\bMrs\\.?\\s?Claus\\b',
    '\\bMistletoe\\b',
    '\\bYuletide\\b',
    '\\bElf\\b',
    '\\bReindeer\\b',
    '\\bFrosty\\b',
    '\\bSnow(?:man)?\\b',
    '\\bSleigh\\b',
    '\\bJingle Bells?\\b',
    '\\bNativity\\b',
    '\\bCarol\\b',
    '\\bSecret Santa\\b',
  ],
  Thanksgiving: [
    '\\bThanksgiving\\b',
    '\\bFriendsgiving\\b',
    '\\bTurkey\\b',
    '\\bPilgrim[s]?\\b',
    '\\bStuffing\\b',
    '\\bCranberries?\\b',
    '\\bCornucopia\\b',
    '\\bFeast\\b',
    '\\bGravy\\b',
    '\\bGobble\\b',
    '\\bHarvest\\b',
    "\\bMacy'?s\\b",
  ],
  Halloween: [
    '\\bHallowe?en\\b',
    'Treehouse of Horror',
    '\\bSpooktacular\\b',
    '\\bJack[- ]o[- ]lantern\\b',
    '\\bTrick[- ]?or[- ]?Treat\\b',
    '\\bPumpkin[s]?\\b',
    'All Hallows',
    'October 31',
    '\\bCostume\\b',
    '\\bCandy\\b',
    '\\bSpooky\\b',
    '\\bScary\\b',
  ],
  'New Years': [
    '\\bNew Year(?:\'?s)?\\b',
    '\\bNew Year(?:\'?s)? Eve\\b',
    '\\bCountdown\\b',
    '\\bMidnight\\b',
    '\\bChampagne\\b',
    '\\bFireworks\\b',
    '\\bResolution[s]?\\b',
    'Auld Lang Syne',
    'Times Square',
    '\\bBall Drop\\b',
  ],
  Hanukkah: [
    '\\bHanukkah\\b',
    '\\bChanukah\\b',
    '\\bMenorah\\b',
    '\\bDreidel\\b',
    '\\bLatke[s]?\\b',
    '\\bGelt\\b',
    '\\bFestival of Lights\\b',
    '\\bMaccabee[s]?\\b',
  ],
  Kwanzaa: [
    '\\bKwanzaa\\b',
    '\\bKinara\\b',
    '\\bUjamaa\\b',
    '\\bKaramu\\b',
    'Seven Principles',
  ],
  Easter: [
    '\\bEaster\\b',
    '\\bEaster Egg\\b',
    '\\bEaster Bunny\\b',
    '\\bEgg Hunt\\b',
    '\\bPastel\\b',
    '\\bSpring\\b',
    '\\bBasket\\b',
    '\\bChick[s]?\\b',
    '\\bRabbit\\b',
  ],
  "Valentine's Day": [
    "\\bValentine'?s?\\b",
    '\\bCupid\\b',
    '\\bRomance\\b',
    '\\bSweetheart\\b',
    '\\bBe My Valentine\\b',
    '\\bDate Night\\b',
    '\\bSecret Admirer\\b',
    '\\bChocolate\\b',
    '\\bRose?s?\\b',
    '\\bCandy Hearts?\\b',
    '\\bLove\\b',
  ],
  'Independence Day': [
    '\\bIndependence Day\\b',
    '\\bFourth of July\\b',
    '\\b4th of July\\b',
    '\\bJuly 4\\b',
    '\\bFireworks\\b',
    '\\bBBQ\\b',
    '\\bBarbeque\\b',
    '\\bPatriotic\\b',
    '\\bAmerica\\b',
    '\\bFreedom\\b',
    '\\bRed White Blue\\b',
  ],
  "St. Patrick's Day": [
    "\\bSt\\.?\\s?Patrick'?s?\\b",
    '\\bShamrock\\b',
    '\\bLeprechaun\\b',
    '\\bGreen\\b',
    '\\bIrish\\b',
    '\\bClover\\b',
    '\\bPot of Gold\\b',
    '\\bRainbow\\b',
  ],
  'April Fools': [
    "\\bApril Fool'?s?\\b",
    '\\bPrank\\b',
    '\\bJoke\\b',
    '\\bTrick\\b',
    'April 1',
  ],
  "Mother's Day": [
    "\\bMother'?s? Day\\b",
    '\\bMom\\b',
    '\\bMother\\b',
    '\\bMamma\\b',
  ],
  "Father's Day": [
    "\\bFather'?s? Day\\b",
    '\\bDad\\b',
    '\\bFather\\b',
    '\\bPapa\\b',
  ],
  'Labor Day': [
    '\\bLabor Day\\b',
    '\\bLabour Day\\b',
    'September',
    '\\bWorker[s]?\\b',
  ],
  'Memorial Day': [
    '\\bMemorial Day\\b',
    '\\bRemember\\b',
    '\\bVeteran[s]?\\b',
    '\\bFallen\\b',
  ],
  'Veterans Day': [
    '\\bVeterans? Day\\b',
    '\\bArmistice\\b',
    '\\bRemembrance\\b',
    'November 11',
  ],
  'Mardi Gras': [
    '\\bMardi Gras\\b',
    '\\bFat Tuesday\\b',
    '\\bCarnival\\b',
    '\\bBeads\\b',
    '\\bKing Cake\\b',
    '\\bNew Orleans\\b',
    '\\bMask[s]?\\b',
  ],
  'Dia de los Muertos': [
    '\\bDia de los Muertos\\b',
    '\\bDay of the Dead\\b',
    '\\bCalavera\\b',
    '\\bSugar Skull\\b',
    '\\bMarigold\\b',
    '\\bOfrenda\\b',
  ],
  'Chinese New Year': [
    '\\bChinese New Year\\b',
    '\\bLunar New Year\\b',
    '\\bSpring Festival\\b',
    '\\bDragon\\b',
    '\\bLion Dance\\b',
    '\\bRed Envelope\\b',
    '\\bFirecracker\\b',
  ],
  Diwali: [
    '\\bDiwali\\b',
    '\\bDeepavali\\b',
    '\\bFestival of Lights\\b',
    '\\bDiya\\b',
    '\\bRangoli\\b',
  ],
  Ramadan: [
    '\\bRamadan\\b',
    '\\bIftar\\b',
    '\\bSuhoor\\b',
    '\\bFasting\\b',
    '\\bEid\\b',
  ],
  'Winter Holiday': [
    '\\bWinter\\b',
    '\\bSnow\\b',
    '\\bSnowy\\b',
    '\\bFrost\\b',
    '\\bIce\\b',
    '\\bCold\\b',
    '\\bWinter Wonderland\\b',
  ],
  'Generic Holiday': [
    '\\bHoliday\\b',
    '\\bCelebration\\b',
    '\\bFestive\\b',
    '\\bSpecial\\b',
  ],
};

export const EXCLUDE_PATTERNS = [
  '\\bChristmas Island\\b',
  '\\bTurkey (?:vulture|shootout|buzzard|sandwich)\\b',
  '\\bBlack Friday\\b',
  '\\bTalking Turkey\\b',
  '\\bCold Turkey\\b',
  '\\bGhost(?:busters?|writer|town|ship|story)\\b',
  '\\bMonster(?:s? Inc|truck|energy|hunter|high)\\b',
  '\\bSpooky (?:action|distance)\\b',
  '\\bHaunted (?:mansion|house) (?:party|ride|attraction)\\b',
  '\\bCandy (?:cane|shop|store|crush|land|factory)\\b',
  '\\bSkeleton (?:key|crew|coast)\\b',
  '\\bWitch (?:doctor|hazel)\\b',
  '\\bPumpkin (?:spice|pie|patch|head|bread|seeds?)\\b',
  '\\bCostume (?:party|shop|designer|contest|drama)\\b',
  '\\bZombie (?:apocalypse|outbreak|virus|infection|horde)\\b',
];

export const PLAYLIST_PREFIX = 'Holiday – ';

export const DEFAULT_TV_LIBRARY = 'TV Shows';
export const DEFAULT_MOVIE_LIBRARY = 'Movies';

export const SCRAPE_CACHE_TTL = 7 * 24 * 60 * 60 * 1000; // 7 days in milliseconds
