import { Holiday } from '@/types';

export const HOLIDAY_EMOJIS: Record<Holiday, string> = {
  'Christmas': '🎄',
  'Thanksgiving': '🦃',
  'Halloween': '🎃',
  'New Years': '🎊',
  'Hanukkah': '🕎',
  'Kwanzaa': '🕯️',
  'Easter': '🐰',
  'Valentine\'s Day': '💝',
  'Independence Day': '🎆',
  'St. Patrick\'s Day': '☘️',
  'April Fools': '🤡',
  'Mother\'s Day': '💐',
  'Father\'s Day': '👔',
  'Labor Day': '🛠️',
  'Memorial Day': '🎖️',
  'Veterans Day': '🇺🇸',
  'Mardi Gras': '🎭',
  'Dia de los Muertos': '💀',
  'Chinese New Year': '🧧',
  'Diwali': '🪔',
  'Ramadan': '🌙',
  'Winter Holiday': '❄️',
  'Generic Holiday': '🎉',
};

export const ALL_HOLIDAYS: Holiday[] = [
  'Christmas',
  'Thanksgiving',
  'Halloween',
  'New Years',
  'Hanukkah',
  'Kwanzaa',
  'Easter',
  'Valentine\'s Day',
  'Independence Day',
  'St. Patrick\'s Day',
  'April Fools',
  'Mother\'s Day',
  'Father\'s Day',
  'Labor Day',
  'Memorial Day',
  'Veterans Day',
  'Mardi Gras',
  'Dia de los Muertos',
  'Chinese New Year',
  'Diwali',
  'Ramadan',
  'Winter Holiday',
  'Generic Holiday',
];
