import { Holiday } from '@/types';

/**
 * Required movies that must always be included in holiday playlists
 * These are prioritized above Wikipedia scraping and keyword matching
 */
export const REQUIRED_MOVIES: Record<Holiday, Array<{ title: string; year: number }>> = {
  Halloween: [
    { title: 'Das Cabinet des Dr. Caligari', year: 1920 },
    { title: 'Der Golem, wie er in die Welt kam', year: 1920 },
    { title: 'Haunted Spooks', year: 1920 },
    { title: 'The Cabinet of Dr. Caligari', year: 1920 },
    { title: 'The Golem', year: 1920 },
    { title: 'Körkarlen', year: 1921 },
    { title: 'The Haunted House', year: 1921 },
    { title: 'The Phantom Carriage', year: 1921 },
    { title: 'Häxan', year: 1922 },
    { title: 'Nosferatu', year: 1922 },
    { title: 'Nosferatu, eine Symphonie des Grauens', year: 1922 },
    { title: 'Witchcraft Through the Ages', year: 1922 },
    { title: 'The Hunchback of Notre Dame', year: 1923 },
    { title: "Orlac\'s Hände", year: 1924 },
    { title: 'Orlacs Hände', year: 1924 },
    { title: 'The Hands of Orlac', year: 1924 },
    { title: 'The Phantom of the Opera', year: 1925 },
    { title: 'A Page of Madness', year: 1926 },
    { title: 'Faust - Eine deutsche Volkssage', year: 1926 },
    { title: 'Faust: A German Folk Legend', year: 1926 },
    { title: 'Kurutta ippêji', year: 1926 },
    { title: 'The Bat', year: 1926 },
    { title: 'The Cat and the Canary', year: 1927 },
    { title: 'The Unknown', year: 1927 },
    { title: 'La chute de la maison Usher', year: 1928 },
    { title: 'The Fall of the House of Usher', year: 1928 },
    { title: 'The Man Who Laughs', year: 1928 },
    { title: 'An Andalusian Dog', year: 1929 },
    { title: 'The Skeleton Dance', year: 1929 },
    { title: 'Un chien andalou', year: 1929 },
    { title: 'Dr. Jekyll and Mr. Hyde', year: 1931 },
    { title: 'Dracula', year: 1931 },
    { title: 'Frankenstein', year: 1931 },
    { title: 'M', year: 1931 },
    { title: 'Freaks', year: 1932 },
    { title: 'Island of Lost Souls', year: 1932 },
    { title: 'The Most Dangerous Game', year: 1932 },
    { title: 'The Mummy', year: 1932 },
    { title: 'The Old Dark House', year: 1932 },
    { title: 'Vampyr', year: 1932 },
    { title: 'White Zombie', year: 1932 },
    { title: "Betty Boop\'s Hallowe\'en Party", year: 1933 },
    { title: 'Das Testament des Dr. Mabuse', year: 1933 },
    { title: 'King Kong', year: 1933 },
    { title: 'The Invisible Man', year: 1933 },
    { title: 'The Testament of Dr. Mabuse', year: 1933 },
    { title: 'The Black Cat', year: 1934 },
    { title: 'Mad Love', year: 1935 },
    { title: 'The Bride of Frankenstein', year: 1935 },
    { title: 'The Cat and the Canary', year: 1939 },
    { title: 'The Hound of the Baskervilles', year: 1939 },
    { title: 'Rebecca', year: 1940 },
    { title: 'The Ghost Breakers', year: 1940 },
    { title: 'Hold That Ghost', year: 1941 },
    { title: 'Spooks Run Wild', year: 1941 },
    { title: 'The Wolf Man', year: 1941 },
    { title: 'Cat People', year: 1942 },
    { title: 'The Boogie Man Will Get You', year: 1942 },
    { title: 'Carnival of Sinners', year: 1943 },
    { title: 'I Walked with a Zombie', year: 1943 },
    { title: 'La main du diable', year: 1943 },
    { title: "The Devil\'s Hand", year: 1943 },
    { title: 'The Leopard Man', year: 1943 },
    { title: 'The Seventh Victim', year: 1943 },
    { title: 'Arsenic and Old Lace', year: 1944 },
    { title: 'Meet Me in St. Louis', year: 1944 },
    { title: 'The Curse of the Cat People', year: 1944 },
    { title: 'The Uninvited', year: 1944 },
    { title: 'Dead of Night', year: 1945 },
    { title: 'Isle of the Dead', year: 1945 },
    { title: 'The Body Snatcher', year: 1945 },
    { title: 'The Picture of Dorian Gray', year: 1945 },
    { title: 'Zombies on Broadway', year: 1945 },
    { title: 'Spook Busters', year: 1946 },
    { title: 'The Spiral Staircase', year: 1946 },
    { title: 'Abbott and Costello Meet Frankenstein', year: 1948 },
    { title: 'Bud Abbott Lou Costello Meet Frankenstein', year: 1948 },
    { title: 'Abbott and Costello Meet the Killer, Boris Karloff', year: 1949 },
    { title: 'The Legend of Sleepy Hollow', year: 1949 },
    { title: 'Love at First Bite', year: 1950 },
    { title: 'The Thing from Another World', year: 1951 },
    { title: 'The White Reindeer', year: 1952 },
    { title: 'Trick or Treat', year: 1952 },
    { title: 'Valkoinen peura', year: 1952 },
    { title: 'Abbott and Costello Meet Dr. Jekyll and Mr. Hyde', year: 1953 },
    { title: 'It Came from Outer Space', year: 1953 },
    { title: 'Scared Stiff', year: 1953 },
    { title: 'Tales of Ugetsu', year: 1953 },
    { title: 'The Tell-Tale Heart', year: 1953 },
    { title: 'Ugetsu monogatari', year: 1953 },
    { title: 'Creature from the Black Lagoon', year: 1954 },
    { title: 'Godzilla', year: 1954 },
    { title: 'Gojira', year: 1954 },
    { title: 'Rear Window', year: 1954 },
    { title: 'Them!', year: 1954 },
    { title: 'Abbott and Costello Meet the Mummy', year: 1955 },
    { title: 'Daughter of Horror', year: 1955 },
    { title: 'Dementia', year: 1955 },
    { title: 'Diabolique', year: 1955 },
    { title: 'Les Diaboliques', year: 1955 },
    { title: 'Tarantula', year: 1955 },
    { title: 'The Night of the Hunter', year: 1955 },
    { title: 'Broom-Stick Bunny', year: 1956 },
    { title: 'Francis in the Haunted House', year: 1956 },
    { title: 'Invasion of the Body Snatchers', year: 1956 },
    { title: 'The Bad Seed', year: 1956 },
    { title: 'Curse of the Demon', year: 1957 },
    { title: 'I Was a Teenage Werewolf', year: 1957 },
    { title: 'Night of the Demon', year: 1957 },
    { title: 'The Incredible Shrinking Man', year: 1957 },
    { title: 'De dødes tjern', year: 1958 },
    { title: 'Dracula', year: 1958 },
    { title: 'Horror of Dracula', year: 1958 },
    { title: 'Lake of the Dead', year: 1958 },
    { title: 'The Blob', year: 1958 },
    { title: 'The Return of Dracula', year: 1958 },
    { title: 'A Bucket of Blood', year: 1959 },
    { title: 'House on Haunted Hill', year: 1959 },
    { title: 'The Hound of the Baskervilles', year: 1959 },
    { title: 'The Mummy', year: 1959 },
    { title: 'The Tingler', year: 1959 },
    { title: 'Black Sunday', year: 1960 },
    { title: 'Eyes Without a Face', year: 1960 },
    { title: 'La maschera del demonio', year: 1960 },
    { title: 'Les yeux sans visage', year: 1960 },
    { title: 'Peeping Tom', year: 1960 },
    { title: 'Psycho', year: 1960 },
    { title: 'The Little Shop of Horrors', year: 1960 },
    { title: 'The Mask of Satan', year: 1960 },
    { title: 'Village of the Damned', year: 1960 },
    { title: 'Matka Joanna od aniołów', year: 1961 },
    { title: 'Mother Joan of the Angels', year: 1961 },
    { title: 'Scream of Fear', year: 1961 },
    { title: 'Taste of Fear', year: 1961 },
    { title: 'The Beast of Yucca Flats', year: 1961 },
    { title: 'The Innocents', year: 1961 },
    { title: 'The Pit and the Pendulum', year: 1961 },
    { title: 'Carnival of Souls', year: 1962 },
    { title: 'To Kill a Mockingbird', year: 1962 },
    { title: 'What Ever Happened to Baby Jane?', year: 1962 },
    { title: 'Black Sabbath', year: 1963 },
    { title: 'Evil Eye', year: 1963 },
    { title: 'I tre volti della paura', year: 1963 },
    { title: 'Il demonio', year: 1963 },
    { title: 'La frusta e il corpo', year: 1963 },
    { title: 'La ragazza che sapeva troppo', year: 1963 },
    { title: 'The Birds', year: 1963 },
    { title: 'The Comedy of Terrors', year: 1963 },
    { title: 'The Demon', year: 1963 },
    { title: 'The Girl Who Knew Too Much', year: 1963 },
    { title: 'The Haunting', year: 1963 },
    { title: 'The Old Dark House', year: 1963 },
    { title: 'The Raven', year: 1963 },
    { title: 'The Whip and the Body', year: 1963 },
    { title: 'Blood and Black Lace', year: 1964 },
    { title: 'Devil Woman', year: 1964 },
    { title: 'Ghost Stories', year: 1964 },
    { title: 'Kaidan', year: 1964 },
    { title: 'Kwaidan', year: 1964 },
    { title: 'Onibaba', year: 1964 },
    { title: 'Seance on a Wet Afternoon', year: 1964 },
    { title: "Sei donne per l\'assassino", year: 1964 },
    { title: 'Suna no onna', year: 1964 },
    { title: 'The Masque of the Red Death', year: 1964 },
    { title: 'Woman in the Dunes', year: 1964 },
    { title: 'Corn on the Cop', year: 1965 },
    { title: 'Repulsion', year: 1965 },
    { title: 'The Collector', year: 1965 },
    { title: 'Carry on Screaming!', year: 1966 },
    { title: "It\'s the Great Pumpkin, Charlie Brown", year: 1966 },
    { title: 'Kill, Baby... Kill!', year: 1966 },
    { title: 'Operazione paura', year: 1966 },
    { title: 'Seconds', year: 1966 },
    { title: 'Tanin no kao', year: 1966 },
    { title: 'The Face of Another', year: 1966 },
    { title: 'Dance of the Vampires', year: 1967 },
    { title: 'Hillbillys in a Haunted House', year: 1967 },
    { title: 'The Fearless Vampire Killers', year: 1967 },
    { title: 'The Spirit of Evil', year: 1967 },
    { title: 'Viy', year: 1967 },
    { title: 'Wait Until Dark', year: 1967 },
    { title: 'A Black Cat in a Bamboo Grove', year: 1968 },
    { title: 'A Quiet Place In the Country', year: 1968 },
    { title: 'Hour of the Wolf', year: 1968 },
    { title: 'Night of the Living Dead', year: 1968 },
    { title: "Rosemary\'s Baby", year: 1968 },
    { title: 'Spider Baby or, The Maddest Story Ever Told', year: 1968 },
    { title: 'Targets', year: 1968 },
    { title: 'The Conqueror Worm', year: 1968 },
    { title: 'The Devil Rides Out', year: 1968 },
    { title: "The Devil\'s Bride", year: 1968 },
    { title: 'Un tranquillo posto di campagna', year: 1968 },
    { title: 'Vargtimmen', year: 1968 },
    { title: 'Witchfinder General', year: 1968 },
    { title: 'Yabu no naka no kuroneko', year: 1968 },
    { title: 'Blind Beast', year: 1969 },
    { title: 'La residencia', year: 1969 },
    { title: 'Môjû', year: 1969 },
    { title: 'Spalovac mrtvol', year: 1969 },
    { title: 'The Boarding School', year: 1969 },
    { title: 'The Cremator', year: 1969 },
    { title: 'The House That Screamed', year: 1969 },
    { title: "L\'uccello dalle piume di cristallo", year: 1970 },
    { title: 'The Bird with the Crystal Plumage', year: 1970 },
    { title: 'The Grandmother', year: 1970 },
    { title: 'The Vampire Lovers', year: 1970 },
    { title: 'Valerie a týden divu', year: 1970 },
    { title: 'Valerie and Her Week of Wonders', year: 1970 },
    { title: 'A Bay of Blood', year: 1971 },
    { title: 'Caged Virgins', year: 1971 },
    { title: 'Daughters of Darkness', year: 1971 },
    { title: 'Demons', year: 1971 },
    { title: 'Duel', year: 1971 },
    { title: 'Ecologia del delitto', year: 1971 },
    { title: 'Les lèvres rouges', year: 1971 },
    { title: 'Lesbian Vampires: The Heiress of Dracula', year: 1971 },
    { title: "Let\'s Scare Jessica to Death", year: 1971 },
    { title: 'Reazione a catena', year: 1971 },
    { title: 'Requiem For A Vampire', year: 1971 },
    { title: 'Requiem pour un vampire', year: 1971 },
    { title: 'Shura', year: 1971 },
    { title: 'The Abominable Dr. Phibes', year: 1971 },
    { title: 'The Devils', year: 1971 },
    { title: 'The Return of Count Yorga', year: 1971 },
    { title: 'The Third Part of the Night', year: 1971 },
    { title: 'Trzecia część nocy', year: 1971 },
    { title: 'Twitch of the Death Nerve', year: 1971 },
    { title: 'Vampyros Lesbos', year: 1971 },
    { title: 'Wake in Fright', year: 1971 },
    { title: 'Delirio caldo', year: 1972 },
    { title: 'Delirium', year: 1972 },
    { title: 'Diabeł', year: 1972 },
    { title: 'Images', year: 1972 },
    { title: 'La Cabina', year: 1972 },
    { title: 'Morgiana', year: 1972 },
    { title: 'Private Parts', year: 1972 },
    { title: 'Sisters', year: 1972 },
    { title: 'The Devil', year: 1972 },
    { title: 'The Last House on the Left', year: 1972 },
    { title: 'The Telephone Box', year: 1972 },
    { title: 'Carnal Violence', year: 1973 },
    { title: 'Dead People', year: 1973 },
    { title: "Don\'t Look Now", year: 1973 },
    { title: 'I corpi presentano tracce di violenza carnale', year: 1973 },
    { title: 'La Rose De Fer', year: 1973 },
    { title: 'Messiah of Evil', year: 1973 },
    { title: "Please Don\'t Eat My Mother", year: 1973 },
    { title: 'Sanatorium pod klepsydrą', year: 1973 },
    { title: 'The Exorcist', year: 1973 },
    { title: 'The Hourglass Sanatorium', year: 1973 },
    { title: 'The Iron Rose', year: 1973 },
    { title: 'The Wicker Man', year: 1973 },
    { title: 'Torso', year: 1973 },
    { title: 'Black Christmas', year: 1974 },
    { title: 'Let Sleeping Corpses Lie', year: 1974 },
    { title: 'Non si deve profanare il sonno dei morti', year: 1974 },
    { title: 'Phantom of the Paradise', year: 1974 },
    { title: 'Phase IV', year: 1974 },
    { title: 'The Cars That Ate Paris', year: 1974 },
    { title: 'The Living Dead at Manchester Morgue', year: 1974 },
    { title: 'The Texas Chain Saw Massacre', year: 1974 },
    { title: 'The Texas Chainsaw Massacre', year: 1974 },
    { title: 'Young Frankenstein', year: 1974 },
    { title: 'Deep Red', year: 1975 },
    { title: 'Jaws', year: 1975 },
    { title: 'Picnic at Hanging Rock', year: 1975 },
    { title: 'Profondo rosso', year: 1975 },
    { title: 'Shivers', year: 1975 },
    { title: 'The Rocky Horror Picture Show', year: 1975 },
    { title: 'The Stepford Wives', year: 1975 },
    { title: 'They Came from Within', year: 1975 },
    { title: '¿Quién puede matar a un niño?', year: 1976 },
    { title: 'Carrie', year: 1976 },
    { title: 'Island of the Damned', year: 1976 },
    { title: 'Kenny & Company', year: 1976 },
    { title: 'La casa dalle finestre che ridono', year: 1976 },
    { title: 'Le locataire', year: 1976 },
    { title: 'Murder by Death', year: 1976 },
    { title: 'The Clown Murders', year: 1976 },
    { title: 'The House with Laughing Windows', year: 1976 },
    { title: 'The Little Girl Who Lives Down the Lane', year: 1976 },
    { title: 'The Omen', year: 1976 },
    { title: 'The Paul Lynde Halloween Special', year: 1976 },
    { title: 'The Signalman', year: 1976 },
    { title: 'The Tenant', year: 1976 },
    { title: 'Who Can Kill a Child?', year: 1976 },
    { title: "Bugs Bunny\'s Howl-oween Special", year: 1977 },
    { title: 'Eraserhead', year: 1977 },
    { title: 'Exorcist II: The Heretic', year: 1977 },
    { title: 'Halloween Is Grinch Night', year: 1977 },
    { title: 'Halloween with the New Addams Family', year: 1977 },
    { title: 'Hausu', year: 1977 },
    { title: 'House', year: 1977 },
    { title: 'Ieoh Island', year: 1977 },
    { title: 'Io Island', year: 1977 },
    { title: 'Iodo', year: 1977 },
    { title: 'Martin', year: 1977 },
    { title: 'Rabid', year: 1977 },
    { title: 'Sighs', year: 1977 },
    { title: 'Suspiria', year: 1977 },
    { title: 'The Fat Albert Halloween Special', year: 1977 },
    { title: 'Ai no bôrei', year: 1978 },
    { title: 'Attack of the Killer Tomatoes!', year: 1978 },
    { title: 'Beauty and the Beast', year: 1978 },
    { title: 'Dawn of the Dead', year: 1978 },
    { title: 'Empire of Passion', year: 1978 },
    { title: 'Halloween', year: 1978 },
    { title: 'Invasion of the Body Snatchers', year: 1978 },
    { title: 'Les raisins de la mort', year: 1978 },
    { title: 'Panna a netvor', year: 1978 },
    { title: 'Piranha', year: 1978 },
    { title: 'The Fury', year: 1978 },
    { title: 'The Grapes of Death', year: 1978 },
    { title: 'The Medusa Touch', year: 1978 },
    { title: 'The Shout', year: 1978 },
    { title: "Witch\'s Night Out", year: 1978 },
    { title: 'Alien', year: 1979 },
    { title: 'Arrebato', year: 1979 },
    { title: "Casper the Friendly Ghost: He Ain't Scary, He's Our Brother", year: 1979 },
    { title: 'Love at First Bite', year: 1979 },
    { title: 'Nosferatu the Vampyre', year: 1979 },
    { title: 'Nosferatu: Phantom der Nacht', year: 1979 },
    { title: 'Nosferatu: Phantom of the Night', year: 1979 },
    { title: 'Phantasm', year: 1979 },
    { title: 'Rapture', year: 1979 },
    { title: "Salem\'s Lot", year: 1979 },
    { title: 'Schalcken the Painter', year: 1979 },
    { title: 'The Amityville Horror', year: 1979 },
    { title: 'The Brood', year: 1979 },
    { title: "The Halloween That Almost Wasn\'t", year: 1979 },
    { title: 'Zombi 2', year: 1979 },
    { title: 'Zombie', year: 1979 },
    { title: 'Zombie Flesh Eaters', year: 1979 },
    { title: 'Alligator', year: 1980 },
    { title: 'Altered States', year: 1980 },
    { title: 'Cannibal Holocaust', year: 1980 },
    { title: 'City of the Living Dead', year: 1980 },
    { title: 'Dressed to Kill', year: 1980 },
    { title: 'Friday the 13th', year: 1980 },
    { title: 'Inferno', year: 1980 },
    { title: 'Maniac', year: 1980 },
    { title: 'Motel Hell', year: 1980 },
    { title: 'Paura nella Città dei Morti Viventi', year: 1980 },
    { title: 'The Changeling', year: 1980 },
    { title: 'The Fog', year: 1980 },
    { title: 'The Gates of Hell', year: 1980 },
    { title: 'The Hollywood Knights', year: 1980 },
    { title: 'The Shining', year: 1980 },
    { title: "...E tu vivrai nel terrore! L\'aldilà", year: 1981 },
    { title: 'An American Werewolf in London', year: 1981 },
    { title: 'Dark Night of the Scarecrow', year: 1981 },
    { title: 'Docteur Jekyll et les femmes', year: 1981 },
    { title: 'Halloween II', year: 1981 },
    { title: 'Possession', year: 1981 },
    { title: 'Scanners', year: 1981 },
    { title: 'Shock Treatment', year: 1981 },
    { title: 'Student Bodies', year: 1981 },
    { title: 'The Beyond', year: 1981 },
    { title: 'The Evil Dead', year: 1981 },
    { title: 'The Howling', year: 1981 },
    { title: 'The Strange Case of Dr. Jekyll and Miss Osbourne', year: 1981 },
    { title: 'Basket Case', year: 1982 },
    { title: 'Cat People', year: 1982 },
    { title: 'Class Reunion', year: 1982 },
    { title: 'Creepshow', year: 1982 },
    { title: 'Der Fan', year: 1982 },
    { title: "Disney\'s Halloween Treat", year: 1982 },
    { title: 'E.T.: The Extra-Terrestrial', year: 1982 },
    { title: 'Halloween III: Season of the Witch', year: 1982 },
    { title: "National Lampoon\'s Class Reunion", year: 1982 },
    { title: 'Pandemonium', year: 1982 },
    { title: 'Poltergeist', year: 1982 },
    { title: 'Poltergeist', year: 1982 },
    { title: 'Tenebre', year: 1982 },
    { title: 'The Entity', year: 1982 },
    { title: 'The Thing', year: 1982 },
    { title: 'Thursday the 12th', year: 1982 },
    { title: 'Trance', year: 1982 },
    { title: 'Trick or Treats', year: 1982 },
    { title: 'White Dog', year: 1982 },
    { title: 'Angst', year: 1983 },
    { title: 'Christine', year: 1983 },
    { title: 'De Vierde Man', year: 1983 },
    { title: 'Hysterical', year: 1983 },
    { title: 'Michael Jackson: Thriller', year: 1983 },
    { title: 'Microwave Massacre', year: 1983 },
    { title: 'Mo', year: 1983 },
    { title: 'Mr. Mom', year: 1983 },
    { title: 'Psycho II', year: 1983 },
    { title: 'The 4th Man', year: 1983 },
    { title: "The Boxer\'s Omen", year: 1983 },
    { title: 'The Dead Zone', year: 1983 },
    { title: 'The Fourth Man', year: 1983 },
    { title: 'The Great Bear Scare', year: 1983 },
    { title: 'The Hunger', year: 1983 },
    { title: 'The Keep', year: 1983 },
    { title: 'Videodrome', year: 1983 },
    { title: 'A Nightmare on Elm Street', year: 1984 },
    { title: 'Bloodbath at the House of Death', year: 1984 },
    { title: 'Children of the Corn', year: 1984 },
    { title: 'Ghostbusters', year: 1984 },
    { title: 'Gremlins', year: 1984 },
    { title: 'Night of the Comet', year: 1984 },
    { title: 'Rats - Notte di terrore', year: 1984 },
    { title: 'Rats: Night of Terror', year: 1984 },
    { title: 'Surf II: The End of the Trilogy', year: 1984 },
    { title: 'The Terminator', year: 1984 },
    { title: 'The Toxic Avenger', year: 1984 },
    { title: 'Cementerio del terror', year: 1985 },
    { title: 'Cemetery of Terror', year: 1985 },
    { title: 'Come and See', year: 1985 },
    { title: 'Creepers', year: 1985 },
    { title: 'Day of the Dead', year: 1985 },
    { title: 'Dèmoni', year: 1985 },
    { title: 'Demons', year: 1985 },
    { title: 'Fright Night', year: 1985 },
    { title: 'Garfield in Disguise', year: 1985 },
    { title: "Garfield\'s Halloween Adventure", year: 1985 },
    { title: 'Geung si sin sang', year: 1985 },
    { title: 'Idi i smotri', year: 1985 },
    { title: 'Mr. Vampire', year: 1985 },
    { title: 'Once Bitten', year: 1985 },
    { title: 'Phenomena', year: 1985 },
    { title: 'Re-Animator', year: 1985 },
    { title: 'Silver Bullet', year: 1985 },
    { title: 'The Midnight Hour', year: 1985 },
    { title: 'The Return of the Living Dead', year: 1985 },
    { title: 'The Stuff', year: 1985 },
    { title: 'Zombie Apocalypse', year: 1985 },
    { title: 'Aliens', year: 1986 },
    { title: "Class of Nuke \'Em High", year: 1986 },
    { title: 'Deadly Friend', year: 1986 },
    { title: 'Friday the 13th Part VI: Jason Lives', year: 1986 },
    { title: 'Haunted Honeymoon', year: 1986 },
    { title: 'Henry: Portrait of a Serial Killer', year: 1986 },
    { title: 'Krysar', year: 1986 },
    { title: 'Little Shop of Horrors', year: 1986 },
    { title: 'Manhunter', year: 1986 },
    { title: 'Poltergeist II: The Other Side', year: 1986 },
    { title: 'Slaughter High', year: 1986 },
    { title: 'TerrorVision', year: 1986 },
    { title: 'The Fly', year: 1986 },
    { title: 'The Pied Piper', year: 1986 },
    { title: 'The Rat Catcher', year: 1986 },
    { title: 'Trick or Treat', year: 1986 },
    { title: 'Vamp', year: 1986 },
    { title: 'A Nightmare on Elm Street 3: Dream Warriors', year: 1987 },
    { title: 'Angel Heart', year: 1987 },
    { title: 'Anguish', year: 1987 },
    { title: 'Angustia', year: 1987 },
    { title: 'Bad Taste', year: 1987 },
    { title: 'Creepshow 2', year: 1987 },
    { title: 'Deliria', year: 1987 },
    { title: 'Evil Dead 2: Dead by Dawn', year: 1987 },
    { title: 'Evil Dead II', year: 1987 },
    { title: 'Hello Mary Lou: Prom Night II', year: 1987 },
    { title: 'Hellraiser', year: 1987 },
    { title: 'House II: The Second Story', year: 1987 },
    { title: 'I Was a Teenage Zombie', year: 1987 },
    { title: 'In A Glass Cage', year: 1987 },
    { title: 'My Best Friend Is a Vampire', year: 1987 },
    { title: 'Near Dark', year: 1987 },
    { title: 'Opera', year: 1987 },
    { title: 'Predator', year: 1987 },
    { title: 'Prince of Darkness', year: 1987 },
    { title: 'Psychos in Love', year: 1987 },
    { title: 'Redneck Zombies', year: 1987 },
    { title: 'StageFright: Aquarius', year: 1987 },
    { title: 'Street Trash', year: 1987 },
    { title: 'Terror at the Opera', year: 1987 },
    { title: 'The Hidden', year: 1987 },
    { title: 'The Lost Boys', year: 1987 },
    { title: 'The Monster Squad', year: 1987 },
    { title: 'The Witches of Eastwick', year: 1987 },
    { title: 'Tras el cristal', year: 1987 },
    { title: 'Alice', year: 1988 },
    { title: 'Beetlejuice', year: 1988 },
    { title: "Child\'s Play", year: 1988 },
    { title: 'Dead Ringers', year: 1988 },
    { title: 'Elvira, Mistress of the Dark', year: 1988 },
    { title: 'FleshEater', year: 1988 },
    { title: 'Gospodin oformitel', year: 1988 },
    { title: 'Hack-O-Lantern', year: 1988 },
    { title: 'Halloween 4: The Return of Michael Myers', year: 1988 },
    { title: 'Halloween Night', year: 1988 },
    { title: 'High Spirits', year: 1988 },
    { title: 'Hollow Gate', year: 1988 },
    { title: 'Killer Klowns from Outer Space', year: 1988 },
    { title: 'Lady in White', year: 1988 },
    { title: 'Mister Designer', year: 1988 },
    { title: 'Neco z Alenky', year: 1988 },
    { title: 'Night of the Demons', year: 1988 },
    { title: 'Poltergeist III', year: 1988 },
    { title: 'Primal Rage', year: 1988 },
    { title: 'Rage, furia primitiva', year: 1988 },
    { title: 'Return of the Killer Tomatoes!', year: 1988 },
    { title: 'Return of the Living Dead Part II', year: 1988 },
    { title: 'Slugs, muerte viscosa', year: 1988 },
    { title: 'Slugs: The Movie', year: 1988 },
    { title: 'Spoorloos', year: 1988 },
    { title: 'The Blob', year: 1988 },
    { title: 'The Kiss', year: 1988 },
    { title: 'The Serpent and the Rainbow', year: 1988 },
    { title: 'The Vanishing', year: 1988 },
    { title: 'They Live', year: 1988 },
    { title: "Vampire\'s Kiss", year: 1988 },
    { title: 'Waxwork', year: 1988 },
    { title: 'Woodchipper Massacre', year: 1988 },
    { title: 'Zombie Nosh', year: 1988 },
    { title: 'C.H.U.D. II - Bud the Chud', year: 1989 },
    { title: 'Cannibal Women in the Avocado Jungle of Death', year: 1989 },
    { title: 'Chopper Chicks in Zombietown', year: 1989 },
    { title: 'Clownhouse', year: 1989 },
    { title: 'Dead Calm', year: 1989 },
    { title: 'Death Spa', year: 1989 },
    { title: 'Ghostbusters II', year: 1989 },
    { title: 'Halloween 5: The Revenge of Michael Myers', year: 1989 },
    { title: 'Out of the Dark', year: 1989 },
    { title: 'Parents', year: 1989 },
    { title: 'Pet Sematary', year: 1989 },
    { title: 'Santa sangre', year: 1989 },
    { title: 'Society', year: 1989 },
    { title: 'Tetsuo', year: 1989 },
    { title: 'Tetsuo: The Iron Man', year: 1989 },
    { title: "The \'Burbs", year: 1989 },
    { title: 'The Toxic Avenger Part III: The Last Temptation of Toxie', year: 1989 },
    { title: 'The Toxic Avenger, Part II', year: 1989 },
    { title: 'The Woman in Black', year: 1989 },
    { title: 'Arachnophobia', year: 1990 },
    { title: 'Begotten', year: 1990 },
    { title: 'Bride of Re-Animator', year: 1990 },
    { title: "Child\'s Play 2", year: 1990 },
    { title: 'Flatliners', year: 1990 },
    { title: 'Frankenhooker', year: 1990 },
    { title: 'Gremlins 2: The New Batch', year: 1990 },
    { title: 'It', year: 1990 },
    { title: "Jacob\'s Ladder", year: 1990 },
    { title: 'Misery', year: 1990 },
    { title: 'Night of the Living Dead', year: 1990 },
    { title: 'Spaced Invaders', year: 1990 },
    { title: 'Tales from the Darkside: The Movie', year: 1990 },
    { title: 'The Exorcist III', year: 1990 },
    { title: 'The Reflecting Skin', year: 1990 },
    { title: 'The Witches', year: 1990 },
    { title: 'Tremors', year: 1990 },
    { title: 'Troll 2', year: 1990 },
    { title: '964 Pinocchio', year: 1991 },
    { title: 'Cape Fear', year: 1991 },
    { title: "Child\'s Play 3", year: 1991 },
    { title: 'Claymation Comedy of Horrors Show', year: 1991 },
    { title: 'Ernest Scared Stupid', year: 1991 },
    { title: 'Night of the Day of the Dawn of the Son of the Bride of the Return of the Revenge of the Terror of the Attack of the Evil, Mutant, Hellbound, Flesh-Eating Subhumanoid Zombified Living Dead, Part 2: In Shocking 2-D', year: 1991 },
    { title: 'Scary Movie', year: 1991 },
    { title: 'The Addams Family', year: 1991 },
    { title: 'The Last Halloween', year: 1991 },
    { title: 'The People Under the Stairs', year: 1991 },
    { title: 'The Silence of the Lambs', year: 1991 },
    { title: 'The Spider', year: 1991 },
    { title: 'Zirneklis', year: 1991 },
    { title: 'Army of Darkness', year: 1992 },
    { title: 'Braindead', year: 1992 },
    { title: "Bram Stoker\'s Dracula", year: 1992 },
    { title: 'Buffy the Vampire Slayer', year: 1992 },
    { title: "C\'est arrivé près de chez vous", year: 1992 },
    { title: 'Candyman', year: 1992 },
    { title: 'Dead Alive', year: 1992 },
    { title: 'Death Becomes Her', year: 1992 },
    { title: 'Demonic Toys', year: 1992 },
    { title: 'Dr. Giggles', year: 1992 },
    { title: 'Dracula', year: 1992 },
    { title: 'Ghostwatch', year: 1992 },
    { title: 'Leprechaun', year: 1992 },
    { title: 'Man Bites Dog', year: 1992 },
    { title: 'Pet Sematary II', year: 1992 },
    { title: 'Pet Sematary II', year: 1992 },
    { title: 'Sleepwalkers', year: 1992 },
    { title: 'The Vagrant', year: 1992 },
    { title: 'Twin Peaks: Fire Walk with Me', year: 1992 },
    { title: 'Addams Family Values', year: 1993 },
    { title: 'Cronos', year: 1993 },
    { title: 'Hocus Pocus', year: 1993 },
    { title: 'Johnny Zombie', year: 1993 },
    { title: 'Jurassic Park', year: 1993 },
    { title: "My Boyfriend\'s Back", year: 1993 },
    { title: 'The Halloween Tree', year: 1993 },
    { title: 'The Nightmare Before Christmas', year: 1993 },
    { title: 'Cemetery Man', year: 1994 },
    { title: 'Dellamorte Dellamore', year: 1994 },
    { title: 'Frankenstein', year: 1994 },
    { title: 'Friday the 13th: Halloween Night', year: 1994 },
    { title: 'In the Mouth of Madness', year: 1994 },
    { title: 'Interview with the Vampire: The Vampire Chronicles', year: 1994 },
    { title: "Mary Shelley\'s Frankenstein", year: 1994 },
    { title: 'Nattevagten', year: 1994 },
    { title: 'New Nightmare', year: 1994 },
    { title: 'Night of the Demons 2', year: 1994 },
    { title: 'Nightwatch', year: 1994 },
    { title: 'Riget', year: 1994 },
    { title: 'Texas Chainsaw Massacre - The Next Generation', year: 1994 },
    { title: 'The Crow', year: 1994 },
    { title: 'The Kingdom', year: 1994 },
    { title: 'The Return of the Texas Chainsaw Massacre', year: 1994 },
    { title: 'Casper', year: 1995 },
    { title: 'Dracula: Dead and Loving It', year: 1995 },
    { title: 'El día de la bestia', year: 1995 },
    { title: 'Evil Ed', year: 1995 },
    { title: 'Grumpier Old Men', year: 1995 },
    { title: 'Halloween: The Curse of Michael Myers', year: 1995 },
    { title: 'Jack-O', year: 1995 },
    { title: 'La cité des enfants perdus', year: 1995 },
    { title: 'Monster Mash: The Movie', year: 1995 },
    { title: 'Se7en', year: 1995 },
    { title: 'Seven', year: 1995 },
    { title: 'The City of Lost Children', year: 1995 },
    { title: 'The Day of the Beast', year: 1995 },
    { title: 'The Langoliers', year: 1995 },
    { title: 'Vampire in Brooklyn', year: 1995 },
    { title: 'From Dusk Till Dawn', year: 1996 },
    { title: 'Killer Condom', year: 1996 },
    { title: 'Kondom des Grauens', year: 1996 },
    { title: 'Scream', year: 1996 },
    { title: "Season\'s Greetings", year: 1996 },
    { title: 'Tesis', year: 1996 },
    { title: 'The Craft', year: 1996 },
    { title: 'The Frighteners', year: 1996 },
    { title: 'Thesis', year: 1996 },
    { title: 'Tremors II: Aftershocks', year: 1996 },
    { title: 'An American Werewolf in Paris', year: 1997 },
    { title: 'Cube', year: 1997 },
    { title: 'Cure', year: 1997 },
    { title: 'Event Horizon', year: 1997 },
    { title: 'Funny Games', year: 1997 },
    { title: 'I Know What You Did Last Summer', year: 1997 },
    { title: 'Kyua', year: 1997 },
    { title: 'Lost Highway', year: 1997 },
    { title: 'Night of the Demons 3', year: 1997 },
    { title: 'Pâfekuto burû', year: 1997 },
    { title: 'Perfect Blue', year: 1997 },
    { title: 'Scream 2', year: 1997 },
    { title: 'Wishmaster', year: 1997 },
    { title: '* Serial Experiments Lain', year: 1998 },
    { title: 'Beloved', year: 1998 },
    { title: 'Bio-Zombie', year: 1998 },
    { title: 'Bride of Chucky', year: 1998 },
    { title: 'Choyonghan kajok', year: 1998 },
    { title: 'Halloween H20: 20 Years Later', year: 1998 },
    { title: 'Halloweentown', year: 1998 },
    { title: 'Pi', year: 1998 },
    { title: 'Ring', year: 1998 },
    { title: 'Ringu', year: 1998 },
    { title: 'Sang faa sau see', year: 1998 },
    { title: 'Sombre', year: 1998 },
    { title: 'The Quiet Family', year: 1998 },
    { title: 'π', year: 1998 },
    { title: 'Audition', year: 1999 },
    { title: "Don\'t Look Under the Bed", year: 1999 },
    { title: 'eXistenZ', year: 1999 },
    { title: 'Eyes Wide Shut', year: 1999 },
    { title: 'Idle Hands', year: 1999 },
    { title: 'Ôdishon', year: 1999 },
    { title: 'Outer Space', year: 1999 },
    { title: 'Ravenous', year: 1999 },
    { title: 'Sleepy Hollow', year: 1999 },
    { title: 'Terror Firmer', year: 1999 },
    { title: 'The Blair Witch Project', year: 1999 },
    { title: 'The Rage: Carrie 2', year: 1999 },
    { title: 'The Sixth Sense', year: 1999 },
    { title: 'Wild Zero', year: 1999 },
    { title: 'American Psycho', year: 2000 },
    { title: 'Batoru rowaiaru', year: 2000 },
    { title: 'Battle Royale', year: 2000 },
    { title: 'Citizen Toxie: The Toxic Avenger IV', year: 2000 },
    { title: 'Final Destination', year: 2000 },
    { title: 'Ginger Snaps', year: 2000 },
    { title: 'Junk', year: 2000 },
    { title: 'Junk: Shiryô-gari', year: 2000 },
    { title: 'Little Otik', year: 2000 },
    { title: 'Machine Head', year: 2000 },
    { title: 'Otesánek', year: 2000 },
    { title: 'Psycho Beach Party', year: 2000 },
    { title: 'Scary Movie', year: 2000 },
    { title: 'Scream 3', year: 2000 },
    { title: 'Shadow of the Vampire', year: 2000 },
    { title: 'The Cell', year: 2000 },
    { title: 'The Little Vampire', year: 2000 },
    { title: 'Vampire Hunter D: Bloodlust', year: 2000 },
    { title: '13 Ghosts', year: 2001 },
    { title: 'Body Jumper', year: 2001 },
    { title: 'Cowboy Bebop: The Movie', year: 2001 },
    { title: 'Donnie Darko', year: 2001 },
    { title: 'El espinazo del diablo', year: 2001 },
    { title: "Elvira\'s Haunted Hills", year: 2001 },
    { title: 'Frailty', year: 2001 },
    { title: "Halloweentown II: Kalabar\'s Revenge", year: 2001 },
    { title: 'How High', year: 2001 },
    { title: 'Ichi the Killer', year: 2001 },
    { title: 'Kairo', year: 2001 },
    { title: 'Katakuri-ke no kôfuku', year: 2001 },
    { title: 'Kaubôi bibappu: Tengoku no tobira', year: 2001 },
    { title: 'Koroshiya 1', year: 2001 },
    { title: 'Mulholland Dr.', year: 2001 },
    { title: 'Mulholland Drive', year: 2001 },
    { title: 'Pop weed sayong', year: 2001 },
    { title: 'Pulse', year: 2001 },
    { title: 'Scary Movie 2', year: 2001 },
    { title: 'Session 9', year: 2001 },
    { title: "The Devil\'s Backbone", year: 2001 },
    { title: 'The Happiness of the Katakuris', year: 2001 },
    { title: 'The Others', year: 2001 },
    { title: 'Thir13en Ghosts', year: 2001 },
    { title: 'Tremors 3: Back to Perfection', year: 2001 },
    { title: 'Trouble Every Day', year: 2001 },
    { title: 'When Good Ghouls Go Bad', year: 2001 },
    { title: '28 Days Later...', year: 2002 },
    { title: 'A New Life', year: 2002 },
    { title: 'Blood Feast 2: All U Can Eat', year: 2002 },
    { title: 'Bubba Ho-tep', year: 2002 },
    { title: 'Carrie', year: 2002 },
    { title: 'Dark Water', year: 2002 },
    { title: 'Dog Soldiers', year: 2002 },
    { title: "Dracula: Pages from a Virgin\'s Diary", year: 2002 },
    { title: 'Eight Legged Freaks', year: 2002 },
    { title: 'Halloween: Resurrection', year: 2002 },
    { title: 'Honogurai mizu no soko kara', year: 2002 },
    { title: 'Irréversible', year: 2002 },
    { title: 'Jisatsu saakuru', year: 2002 },
    { title: 'Ju-on', year: 2002 },
    { title: 'La vie nouvelle', year: 2002 },
    { title: 'May', year: 2002 },
    { title: 'Resident Evil', year: 2002 },
    { title: 'Suicide Club', year: 2002 },
    { title: 'Terror Toons', year: 2002 },
    { title: 'The Collingswood Story', year: 2002 },
    { title: 'The Grudge', year: 2002 },
    { title: 'The Ring', year: 2002 },
    { title: 'A Tale of Two Sisters', year: 2003 },
    { title: 'Battlefield Baseball', year: 2003 },
    { title: 'Beyond Re-Animator', year: 2003 },
    { title: 'Final Destination 2', year: 2003 },
    { title: 'Gokudô Kyôfu dai-gekijô: Gozu', year: 2003 },
    { title: 'Gozu', year: 2003 },
    { title: "Hallow\'s End", year: 2003 },
    { title: 'Haute tension', year: 2003 },
    { title: 'Hey, Stop Stabbing Me!', year: 2003 },
    { title: 'High Tension', year: 2003 },
    { title: 'House of 1000 Corpses', year: 2003 },
    { title: 'Janghwa, Hongryeon', year: 2003 },
    { title: 'Jigoku kôshien', year: 2003 },
    { title: 'Scary Godmother Halloween Spooktakular', year: 2003 },
    { title: 'Scary Movie 3', year: 2003 },
    { title: 'The Haunted Mansion', year: 2003 },
    { title: 'Undead', year: 2003 },
    { title: 'Wasabi Tuna', year: 2003 },
    { title: 'Yakuza Horror Theater', year: 2003 },
    { title: 'Calvaire', year: 2004 },
    { title: 'Choking Hazard', year: 2004 },
    { title: 'Club Dread', year: 2004 },
    { title: 'Dawn of the Dead', year: 2004 },
    { title: 'Dead & Breakfast', year: 2004 },
    { title: 'Dead Scared', year: 2004 },
    { title: 'Dumplings', year: 2004 },
    { title: 'Extreme Halloween', year: 2004 },
    { title: 'Gau ji', year: 2004 },
    { title: 'Ginger Snaps Back: The Beginning', year: 2004 },
    { title: 'Ginger Snaps: Unleashed', year: 2004 },
    { title: 'Halloweentown High', year: 2004 },
    { title: 'HellBent', year: 2004 },
    { title: 'Jiao zi', year: 2004 },
    { title: 'Khun krabii hiiroh', year: 2004 },
    { title: 'Mean Girls', year: 2004 },
    { title: 'Sam gang yi', year: 2004 },
    { title: 'Sars Wars: Bangkok Zombie Crisis', year: 2004 },
    { title: "Satan\'s Little Helper", year: 2004 },
    { title: 'Saw', year: 2004 },
    { title: 'Seed of Chucky', year: 2004 },
    { title: 'Shaun of the Dead', year: 2004 },
    { title: 'Sisily 2km', year: 2004 },
    { title: 'The Hazing', year: 2004 },
    { title: 'The Hollow', year: 2004 },
    { title: 'The Ordeal', year: 2004 },
    { title: 'Three... Extremes', year: 2004 },
    { title: 'To Catch A Virgin Ghost', year: 2004 },
    { title: 'Tremors 4: The Legend Begins', year: 2004 },
    { title: 'Bad Reputation', year: 2005 },
    { title: 'Boo', year: 2005 },
    { title: 'Boy Eats Girl', year: 2005 },
    { title: 'Buppah Rahtree Phase 2: Rahtree Returns', year: 2005 },
    { title: 'Corpse Bride', year: 2005 },
    { title: 'Cry Wolf', year: 2005 },
    { title: 'Cry_Wolf', year: 2005 },
    { title: 'Doll Graveyard', year: 2005 },
    { title: 'Evil Aliens', year: 2005 },
    { title: 'Feast', year: 2005 },
    { title: 'Haze', year: 2005 },
    { title: 'Kimyô na sâkasu', year: 2005 },
    { title: 'Night of the Day of the Dawn of the Son of the Bride of the Return of the Revenge of the Terror of the Attack of the Evil, Mutant, Hellbound, Flesh-Eating Subhumanoid Zombified Living Dead, Part 3', year: 2005 },
    { title: 'Pervert!', year: 2005 },
    { title: "Pooh\'s Heffalump Halloween Movie", year: 2005 },
    { title: 'Pot Zombies', year: 2005 },
    { title: 'Return of the Living Dead: Rave to the Grave', year: 2005 },
    { title: "Santa\'s Slay", year: 2005 },
    { title: 'Son of the Mask', year: 2005 },
    { title: 'Spookley the Square Pumpkin', year: 2005 },
    { title: 'Strange Circus', year: 2005 },
    { title: 'The Amityville Horror', year: 2005 },
    { title: 'The Descent', year: 2005 },
    { title: "The Devil\'s Rejects", year: 2005 },
    { title: 'The Gingerdead Man', year: 2005 },
    { title: 'The Skeleton Key', year: 2005 },
    { title: 'Twitches', year: 2005 },
    { title: 'Wallace & Gromit: The Curse of the Were-Rabbit', year: 2005 },
    { title: 'War of the Worlds', year: 2005 },
    { title: 'Behind the Mask: The Rise of Leslie Vernon', year: 2006 },
    { title: 'Black Sheep', year: 2006 },
    { title: 'Bug', year: 2006 },
    { title: 'Creepshow III', year: 2006 },
    { title: 'Curse of Halloween', year: 2006 },
    { title: 'El laberinto del fauno', year: 2006 },
    { title: 'Evil Bong', year: 2006 },
    { title: 'Fido', year: 2006 },
    { title: 'Frostbiten', year: 2006 },
    { title: 'Frostbitten', year: 2006 },
    { title: 'Gwoemul', year: 2006 },
    { title: 'Halloween Night', year: 2006 },
    { title: 'Hatchet', year: 2006 },
    { title: 'Inland Empire', year: 2006 },
    { title: "Pan\'s Labyrinth", year: 2006 },
    { title: 'Poultrygeist: Night of the Chicken Dead', year: 2006 },
    { title: 'Return to Halloweentown', year: 2006 },
    { title: 'Scary Movie 4', year: 2006 },
    { title: 'Severance', year: 2006 },
    { title: 'Silent Hill', year: 2006 },
    { title: 'Slither', year: 2006 },
    { title: 'Stupid Teenagers Must Die', year: 2006 },
    { title: 'The Hills Have Eyes', year: 2006 },
    { title: 'The Host', year: 2006 },
    { title: 'The Pumpkin Karver', year: 2006 },
    { title: '[Rec]', year: 2007 },
    { title: '1408', year: 2007 },
    { title: '30 Days of Night', year: 2007 },
    { title: "À l\'intérieur", year: 2007 },
    { title: "All Hallows\' Eve", year: 2007 },
    { title: 'Bhool Bhulaiyaa', year: 2007 },
    { title: 'Blood Car', year: 2007 },
    { title: 'Botched', year: 2007 },
    { title: 'El Orfanato', year: 2007 },
    { title: 'Halloween', year: 2007 },
    { title: "Halloween\'s Most Extreme", year: 2007 },
    { title: 'House of Fears', year: 2007 },
    { title: 'Inside', year: 2007 },
    { title: 'Mr. Halloween', year: 2007 },
    { title: 'Murder Party', year: 2007 },
    { title: 'My Name Is Bruce', year: 2007 },
    { title: 'Netherbeast Incorporated', year: 2007 },
    { title: 'Paranormal Activity', year: 2007 },
    { title: 'Planet Terror', year: 2007 },
    { title: 'Pop Skull', year: 2007 },
    { title: 'REC', year: 2007 },
    { title: 'Sweeney Todd: The Demon Barber of Fleet Street', year: 2007 },
    { title: 'Teeth', year: 2007 },
    { title: 'Terror Toons 2', year: 2007 },
    { title: 'The Invasion', year: 2007 },
    { title: 'The Mad', year: 2007 },
    { title: 'The Mist', year: 2007 },
    { title: 'The Orphanage', year: 2007 },
    { title: "Trick \'r Treat", year: 2007 },
    { title: 'Zombie Cheerleader Camp', year: 2007 },
    { title: 'Zombie Cheerleading Camp', year: 2007 },
    { title: 'Baghead', year: 2008 },
    { title: 'Cloverfield', year: 2008 },
    { title: 'Dance of the Dead', year: 2008 },
    { title: "Don\'t Look in the Cellar", year: 2008 },
    { title: 'Eden Lake', year: 2008 },
    { title: 'Feast II: Sloppy Seconds', year: 2008 },
    { title: 'Flick', year: 2008 },
    { title: 'Gingerdead Man 2: Passion of the Crust', year: 2008 },
    { title: 'In Search of Lovecraft', year: 2008 },
    { title: 'Låt den rätte komma in', year: 2008 },
    { title: 'Let the Right One In', year: 2008 },
    { title: 'Lost Boys: The Tribe', year: 2008 },
    { title: 'Martyrs', year: 2008 },
    { title: 'Pontypool', year: 2008 },
    { title: 'Roxy Hunter and the Horrific Halloween', year: 2008 },
    { title: 'The Caretaker', year: 2008 },
    { title: 'The Cottage', year: 2008 },
    { title: 'The Horribly Slow Murderer with the Extremely Inefficient Weapon', year: 2008 },
    { title: 'Trailer Park of Terror', year: 2008 },
    { title: 'Zombie Strippers', year: 2008 },
    { title: 'Amer', year: 2009 },
    { title: 'Antichrist', year: 2009 },
    { title: 'Bakjwi', year: 2009 },
    { title: 'Coraline', year: 2009 },
    { title: 'Dead Snow', year: 2009 },
    { title: 'Død snø', year: 2009 },
    { title: 'Doghouse', year: 2009 },
    { title: 'Drag Me to Hell', year: 2009 },
    { title: 'Evil Bong II: King Bong', year: 2009 },
    { title: 'Feast 3: The Happy Finish', year: 2009 },
    { title: 'Halloween II', year: 2009 },
    { title: 'Halloween in Sleepy Hollow', year: 2009 },
    { title: 'HalloweeNight', year: 2009 },
    { title: 'Heartless', year: 2009 },
    { title: "Jennifer\'s Body", year: 2009 },
    { title: 'Lesbian Vampire Killers', year: 2009 },
    { title: 'Night of the Demons', year: 2009 },
    { title: 'Stan Helsing', year: 2009 },
    { title: 'The House of the Devil', year: 2009 },
    { title: 'The Revenant', year: 2009 },
    { title: 'Thirst', year: 2009 },
    { title: 'Tormented', year: 2009 },
    { title: 'Triangle', year: 2009 },
    { title: 'Where Got Ghost?', year: 2009 },
    { title: 'Xia dao xiao', year: 2009 },
    { title: 'Zombieland', year: 2009 },
    { title: 'Akmareul boatda', year: 2010 },
    { title: 'Black Swan', year: 2010 },
    { title: 'Goblin', year: 2010 },
    { title: "Hallows\' Eve and the Pumpkin Dream", year: 2010 },
    { title: 'I Saw the Devil', year: 2010 },
    { title: 'Insidious', year: 2010 },
    { title: 'Kalevet', year: 2010 },
    { title: 'Let Me In', year: 2010 },
    { title: 'Lost Boys: The Thirst', year: 2010 },
    { title: 'Piranha', year: 2010 },
    { title: 'Piranha 3D', year: 2010 },
    { title: 'Rabies', year: 2010 },
    { title: 'Rare Exports', year: 2010 },
    { title: 'Rubber', year: 2010 },
    { title: 'Scared Shrekless', year: 2010 },
    { title: 'The Troll Hunter', year: 2010 },
    { title: 'Trollhunter', year: 2010 },
    { title: 'Trolljegeren', year: 2010 },
    { title: 'Tucker & Dale vs. Evil', year: 2010 },
    { title: 'A Cadaver Christmas', year: 2011 },
    { title: 'Evil Bong 3: The Wrath of Bong', year: 2011 },
    { title: 'Gingerdead Man 3: Saturday Night Cleaver', year: 2011 },
    { title: 'Halloween (2007) / Halloween II (2009)', year: 2011 },
    { title: 'Juan de los Muertos', year: 2011 },
    { title: 'Juan of the Dead', year: 2011 },
    { title: 'Kill List', year: 2011 },
    { title: 'Killer Eye: Halloween Haunt', year: 2011 },
    { title: 'La piel que habito', year: 2011 },
    { title: 'Legends 2', year: 2011 },
    { title: 'Legends 2 A Halloween Tale', year: 2011 },
    { title: 'Mean Girls 2', year: 2011 },
    { title: 'Mientras duermes', year: 2011 },
    { title: 'Scream 4', year: 2011 },
    { title: 'Sleep Tight', year: 2011 },
    { title: 'The Cabin in the Woods', year: 2011 },
    { title: 'The Dog Who Saved Halloween', year: 2011 },
    { title: 'The Innkeepers', year: 2011 },
    { title: 'The Skin I Live In', year: 2011 },
    { title: 'Violent Night: The Movie', year: 2011 },
    { title: 'We Need to Talk About Kevin', year: 2011 },
    { title: "You\'re Next", year: 2011 },
    { title: '100 Bloody Acres', year: 2012 },
    { title: 'Berberian Sound Studio', year: 2012 },
    { title: 'Citadel', year: 2012 },
    { title: 'First Halloween', year: 2012 },
    { title: 'Fun Size', year: 2012 },
    { title: 'Girls Against Boys', year: 2012 },
    { title: 'Maniac', year: 2012 },
    { title: 'Sightseers', year: 2012 },
    { title: 'Sinister', year: 2012 },
    { title: 'The American Scream', year: 2012 },
    { title: 'The Battery', year: 2012 },
    { title: 'The Collection', year: 2012 },
    { title: 'Truth or Dare', year: 2012 },
    { title: 'Truth or Die', year: 2012 },
    { title: 'V/H/S', year: 2012 },
    { title: 'Wrong Turn 5: Bloodlines', year: 2012 },
    { title: 'A Haunted House', year: 2013 },
    { title: "All Hallows\' Eve", year: 2013 },
    { title: 'Babysitter Massacre', year: 2013 },
    { title: 'Borgman', year: 2013 },
    { title: 'Bunni', year: 2013 },
    { title: 'Carrie', year: 2013 },
    { title: 'Christmaz', year: 2013 },
    { title: 'Gingerdead Man Vs. Evil Bong', year: 2013 },
    { title: 'Grave Halloween', year: 2013 },
    { title: 'Halloween Creep Tales', year: 2013 },
    { title: "Hallows\' Eve", year: 2013 },
    { title: "L\'étrange couleur des larmes de ton corps", year: 2013 },
    { title: 'Mischief Night', year: 2013 },
    { title: 'Oculus', year: 2013 },
    { title: 'Only Lovers Left Alive', year: 2013 },
    { title: 'Scary MoVie', year: 2013 },
    { title: 'Scary Movie 5', year: 2013 },
    { title: 'Texas Chainsaw 3D', year: 2013 },
    { title: 'The Conjuring', year: 2013 },
    { title: "The Strange Color of Your Body\'s Tears", year: 2013 },
    { title: 'Under the Skin', year: 2013 },
    { title: 'Warm Bodies', year: 2013 },
    { title: 'WNUF Halloween Special', year: 2013 },
    { title: 'A Girl Walks Home Alone at Night', year: 2014 },
    { title: 'A Haunted House 2', year: 2014 },
    { title: 'Burying the Ex', year: 2014 },
    { title: 'Buzzard', year: 2014 },
    { title: 'Dead Snow: Red vs. Dead', year: 2014 },
    { title: 'Demonica', year: 2014 },
    { title: 'Død Snø 2', year: 2014 },
    { title: 'Halloween Hell', year: 2014 },
    { title: 'Halloween: The Complete Collection', year: 2014 },
    { title: 'It Follows', year: 2014 },
    { title: 'Life After Beth', year: 2014 },
    { title: 'Mischief Night', year: 2014 },
    { title: 'Over the Garden Wall', year: 2014 },
    { title: 'Summer of Blood', year: 2014 },
    { title: 'The Babadook', year: 2014 },
    { title: 'The Guest', year: 2014 },
    { title: 'The Houses October Built', year: 2014 },
    { title: 'The King and Queen of Halloween', year: 2014 },
    { title: 'The Last Halloween', year: 2014 },
    { title: 'The Scarehouse', year: 2014 },
    { title: 'What We Do in the Shadows', year: 2014 },
    { title: 'Zombeavers', year: 2014 },
    { title: "All Hallows\' Eve 2", year: 2015 },
    { title: 'Bloodsucking Bastards', year: 2015 },
    { title: 'Bone Tomahawk', year: 2015 },
    { title: "Caesar and Otto\'s Paranormal Halloween", year: 2015 },
    { title: 'Crimson Peak', year: 2015 },
    { title: 'Dead Slow Ahead', year: 2015 },
    { title: 'Evil Bong 420', year: 2015 },
    { title: 'February', year: 2015 },
    { title: 'Freaks of Nature', year: 2015 },
    { title: 'Gravy', year: 2015 },
    { title: 'Green Room', year: 2015 },
    { title: 'Halloween Creep Tales 2.0', year: 2015 },
    { title: 'Hell Fire', year: 2015 },
    { title: 'Hell House LLC', year: 2015 },
    { title: 'Hellions', year: 2015 },
    { title: 'Pay the Ghost', year: 2015 },
    { title: 'Poltergeist', year: 2015 },
    { title: 'Poltergeist', year: 2015 },
    { title: 'Riaru onigokko', year: 2015 },
    { title: 'Tag', year: 2015 },
    { title: 'Tales of Halloween', year: 2015 },
    { title: "The Blackcoat\'s Daughter", year: 2015 },
    { title: 'The Funhouse Massacre', year: 2015 },
    { title: 'The Hollow', year: 2015 },
    { title: 'The Invitation', year: 2015 },
    { title: 'The VVitch', year: 2015 },
    { title: 'The Witch: A New-England Folktale', year: 2015 },
    { title: 'Volumes of Blood', year: 2015 },
    { title: '10 Cloverfield Lane', year: 2016 },
    { title: '31', year: 2016 },
    { title: 'Boo! A Madea Halloween', year: 2016 },
    { title: 'Boys in the Trees', year: 2016 },
    { title: 'Busanhaeng', year: 2016 },
    { title: "Don\'t Breathe", year: 2016 },
    { title: 'Evil Bong: High 5', year: 2016 },
    { title: 'Goksung', year: 2016 },
    { title: 'Grave', year: 2016 },
    { title: 'Halloweed', year: 2016 },
    { title: 'Halloween Spookies', year: 2016 },
    { title: 'Halloween: The Night HE Came Back', year: 2016 },
    { title: 'Hallows Eve', year: 2016 },
    { title: 'Holidays', year: 2016 },
    { title: 'House of Purgatory', year: 2016 },
    { title: 'Personal Shopper', year: 2016 },
    { title: 'Raw', year: 2016 },
    { title: 'Terrifier', year: 2016 },
    { title: 'The Barn', year: 2016 },
    { title: 'The Conjuring 2', year: 2016 },
    { title: 'The Halloween Store Zombie Wedding Movie', year: 2016 },
    { title: 'The Neon Demon', year: 2016 },
    { title: 'The Night Before Halloween', year: 2016 },
    { title: 'The Wailing', year: 2016 },
    { title: 'Train to Busan', year: 2016 },
    { title: 'Under the Shadow', year: 2016 },
    { title: '10/31', year: 2017 },
    { title: 'A Holliston Halloween', year: 2017 },
    { title: 'Annabelle: Creation', year: 2017 },
    { title: 'Boo 2! A Madea Halloween', year: 2017 },
    { title: 'Evil Bong 666', year: 2017 },
    { title: "Gerald\'s Game", year: 2017 },
    { title: 'Get Out', year: 2017 },
    { title: 'Halloween Horror at Midnight', year: 2017 },
    { title: 'Halloween Pussy Trap Kill Kill', year: 2017 },
    { title: 'It', year: 2017 },
    { title: 'Kamera o tomeru na!', year: 2017 },
    { title: 'Karpenter', year: 2017 },
    { title: "Michael Jackson\'s Halloween", year: 2017 },
    { title: 'Mother!', year: 2017 },
    { title: 'One Cut of the Dead', year: 2017 },
    { title: 'The Endless', year: 2017 },
    { title: 'The Harvesters', year: 2017 },
    { title: 'The Houses October Built 2', year: 2017 },
    { title: 'The Invoking 4: Halloween Night', year: 2017 },
    { title: 'The Killing of a Sacred Deer', year: 2017 },
    { title: 'The Shape Returns: A Halloween Film', year: 2017 },
    { title: 'Thelma', year: 2017 },
    { title: 'Tokyo Vampire Hotel', year: 2017 },
    { title: 'Tôkyô vanpaia hoteru', year: 2017 },
    { title: 'Truth or Dare', year: 2017 },
    { title: "Tyler Perry\'s Boo 2! A Madea Halloween", year: 2017 },
    { title: 'A Quiet Place', year: 2018 },
    { title: 'American Fright Fest', year: 2018 },
    { title: 'Annihilation', year: 2018 },
    { title: 'Black Pumpkin', year: 2018 },
    { title: 'Cam', year: 2018 },
    { title: 'Climax', year: 2018 },
    { title: 'Fright Fest', year: 2018 },
    { title: 'Goosebumps 2: Haunted Halloween', year: 2018 },
    { title: 'Halloween', year: 2018 },
    { title: "Halloween at Aunt Ethel\'s", year: 2018 },
    { title: 'Halloween Horror Tales', year: 2018 },
    { title: 'Halloween Mind Massacre', year: 2018 },
    { title: 'Halloween Party', year: 2018 },
    { title: 'Hell Fest', year: 2018 },
    { title: 'Hereditary', year: 2018 },
    { title: 'Hurt', year: 2018 },
    { title: 'In Fabric', year: 2018 },
    { title: 'La casa lobo', year: 2018 },
    { title: 'Mandy', year: 2018 },
    { title: 'MVB Films Halloween Horror Stories Vol II', year: 2018 },
    { title: 'Samhain: A Halloween Horror Movie', year: 2018 },
    { title: 'Suspiria', year: 2018 },
    { title: 'The Haunting of Hill House', year: 2018 },
    { title: 'The House That Jack Built', year: 2018 },
    { title: 'The Legend of Halloween Jack', year: 2018 },
    { title: 'The Night Comes for Us', year: 2018 },
    { title: 'The Predator', year: 2018 },
    { title: 'The Wolf House', year: 2018 },
    { title: 'Trico Tri Happy Halloween', year: 2018 },
    { title: 'Unsane', year: 2018 },
    { title: 'When We First Met', year: 2018 },
    { title: '10/31 Part 2', year: 2019 },
    { title: 'Bacurau', year: 2019 },
    { title: 'Candy Corn', year: 2019 },
    { title: 'Deerskin', year: 2019 },
    { title: 'Extra Ordinary', year: 2019 },
    { title: 'Fresh Eggs', year: 2019 },
    { title: 'Giftwrapped & Gutted', year: 2019 },
    { title: 'Giftwrapped and Gutted', year: 2019 },
    { title: 'Halloween Party', year: 2019 },
    { title: 'Haunt', year: 2019 },
    { title: 'It Chapter Two', year: 2019 },
    { title: 'La llorona', year: 2019 },
    { title: 'Le daim', year: 2019 },
    { title: 'Midsommar', year: 2019 },
    { title: 'Paranormal Farm 3 Halloween', year: 2019 },
    { title: 'Ready or Not', year: 2019 },
    { title: 'Scare Package', year: 2019 },
    { title: 'Scary Stories to Tell in the Dark', year: 2019 },
    { title: 'Spine Chiller', year: 2019 },
    { title: 'The Curse of Halloween Jack', year: 2019 },
    { title: 'The Lighthouse', year: 2019 },
    { title: 'The Weeping Woman', year: 2019 },
    { title: 'Trick', year: 2019 },
    { title: 'Us', year: 2019 },
    { title: 'Weedjies: Halloweed Night', year: 2019 },
    { title: 'Zombieland: Double Tap', year: 2019 },
    { title: 'Archaon: The Halloween Summoning', year: 2020 },
    { title: 'Come True', year: 2020 },
    { title: 'Gretel & Hansel', year: 2020 },
    { title: 'Happy Halloween, Scooby-Doo!', year: 2020 },
    { title: 'Harvest of the Dead: Halloween Night', year: 2020 },
    { title: 'Hubie Halloween', year: 2020 },
    { title: 'On Halloween', year: 2020 },
    { title: 'Possessor', year: 2020 },
    { title: 'Possessor: Uncut', year: 2020 },
    { title: 'The Empty Man', year: 2020 },
    { title: 'The Invisible Man', year: 2020 },
    { title: 'They Live Inside Us', year: 2020 },
    { title: 'C.O.R.N. A Field of Screams', year: 2021 },
    { title: 'De uskyldige', year: 2021 },
    { title: 'Frankenstein Ruins Halloween', year: 2021 },
    { title: 'Ghosting Gloria', year: 2021 },
    { title: 'Halloween Heroes', year: 2021 },
    { title: 'Halloween Kickback', year: 2021 },
    { title: 'Halloween Kills', year: 2021 },
    { title: 'Last Night in Soho', year: 2021 },
    { title: 'Legend of Fall Creek', year: 2021 },
    { title: 'Let the Wrong One In', year: 2021 },
    { title: 'Mad God', year: 2021 },
    { title: 'Malignant', year: 2021 },
    { title: 'Muerto con Gloria', year: 2021 },
    { title: 'Old', year: 2021 },
    { title: 'The Innocents', year: 2021 },
    { title: "Willy\'s Wonderland", year: 2021 },
    { title: 'Crimes of the Future', year: 2022 },
    { title: 'Curse of Crom: The Legend of Halloween', year: 2022 },
    { title: 'Cursed Friends', year: 2022 },
    { title: 'Halloween Ends', year: 2022 },
    { title: 'Halloween Jack 3D', year: 2022 },
    { title: 'Hellraiser', year: 2022 },
    { title: 'Invite Only', year: 2022 },
    { title: 'Nope', year: 2022 },
    { title: 'Out There Halloween Mega Tape', year: 2022 },
    { title: 'Sadako DX', year: 2022 },
    { title: 'Satanic Hispanics', year: 2022 },
    { title: 'Skinamarink', year: 2022 },
    { title: 'Spirit Halloween', year: 2022 },
    { title: 'Tales from the Other Side', year: 2022 },
    { title: 'Terrifier 2', year: 2022 },
    { title: 'The Curse of Bridge Hollow', year: 2022 },
    { title: 'Trick or Treat Scooby-Doo!', year: 2022 },
    { title: 'X', year: 2022 },
    { title: 'Appendage', year: 2023 },
    { title: 'Dark Harvest', year: 2023 },
    { title: 'Late Night with the Devil', year: 2023 },
    { title: 'The Toxic Avenger', year: 2023 },
    { title: 'Carved', year: 2024 },
    { title: 'Dressing Up Halloween: The Story of Ben Cooper, Inc.', year: 2024 },
    { title: 'The Bad Guys: Haunted Heist', year: 2024 },
    { title: 'The Substance', year: 2024 },
    { title: 'Haunted House of Pancakes', year: 2025 },
    { title: 'The Monkey', year: 2025 },
    { title: 'Trick or Treat with Reed Richmond', year: 2025 },
  ],
  Thanksgiving: [],
  Christmas: [],
  "Valentine's": [],
};
